name: Front End CI

on:
    pull_request:
    workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Move to Frontend Directory
        run: cd src/angular/osww-frontend

      - name: Setup Node Environment
        uses: actions/setup-node@v4

      - name: Install Dependencies
        run: npm ci

      - name: Run Build
        run: npm run build-arduino
