name: Front End CI

on:
    pull_request:
    workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node Environment
        uses: actions/setup-node@v4

      - name: Install Dependencies
        run: cd src/angular/osww-frontend && npm i

      - name: Create FE Build
        run: cd src/angular/osww-frontend && npm run build-arduino
